# .grype.yaml

fail-on-severity: high

output:
  - table
  - json

# write output report to a file (optional)
# (if you enable this, table output also goes to the file; many teams run json-only to file)
file: ""

db:
  auto-update: true
  # optional if you mount /root/.cache/grype/db like above
  # cache-dir: /root/.cache/grype/db

ignore:
  - vulnerability: CVE-XXXX
    package:
      # in your container workspace, source is under /src
      location: "/src/src/app.js"

log:
  level: info
