# Grype policy configuration
# Enforces consistent vulnerability scanning behaviour

severity-cutoff: high

fail-on:
  - high
  - critical

output:
  - table
  - json

file:
  enabled: true

db:
  auto-update: true

ignore:
  - vulnerability: CVE-XXXX
    file: "src/app.js"


log:
  level: info
